# -*- coding: utf-8 -*-
"""Лабораторная_работа.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/cochelevalexander/6331b627049f229bbe7b3a40315e9c93/-_.ipynb

>ФЕДЕРАЛЬНОЕ ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ
ОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ ВЫСШЕГО ОБРАЗОВАНИЯ
«ОРЛОВСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ И.С.ТУРГЕНЕВА»


> Кафедра «мехатроники, механики и робототехники»





>Лабораторная работа по триботехнике





>Выполнил студент
>Политехнического института
>имени Н.Н.Поликарпова
>студент группы 91-МХ
>Кошелев Александр Сергеевич




>Орёл, 2021
"""

!pip install -Uqq fastbook
import fastbook
fastbook.setup_book()

"""**Импорт библиотек**"""

from fastai.vision.all import*

path = Path('/content/gdrive/MyDrive/Colab Notebooks/tribos/DataSet4/Trianing')
path_all = ('/content/gdrive/MyDrive/Colab Notebooks/tribos/DataSet4/Test')

path.ls()

files = get_image_files(path)

files[0], files[1]

"""**Создание дата сета**

"""

IRI_data =DataBlock(
    blocks= ( ImageBlock, CategoryBlock),
    get_items = get_image_files,
    splitter = RandomSplitter(valid_pct= 0.2, seed = 42),
    get_y = parent_label)

IRI_data = IRI_data.new(item_tfms= Resize(224), batch_tfms= aug_transforms())

dls = IRI_data.dataloaders(path)

from numpy.ma.extras import unique
dls.show_batch(max_n = 9, nrows = 3, unique = True)

learn = cnn_learner(dls, resnet34, metrics= error_rate, pretrained= True, lr = 0.00363)

learn.fine_tune(25)

pred_img = learn.predict(files[100]), files[100]
print(pred_img, files[100])

learn.dls.vocab

learn.show_results()

"""**Оценка точности**

"""

interp = ClassificationInterpretation.from_learner(learn)
a = interp.plot_confusion_matrix()
print(a)

low = interp.confusion_matrix()
fp_sum_fn = sum(sum(low))
tp_sum_tn = sum(np.diagonal(low))
acc = tp_sum_tn/ fp_sum_fn
acc